// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jepbura/go-server/pkg/api"
	"github.com/jepbura/go-server/pkg/api/handler"
	"github.com/jepbura/go-server/pkg/config"
	"github.com/jepbura/go-server/pkg/infrastructure/database/mongo"
	"github.com/jepbura/go-server/pkg/infrastructure/logging"
	"github.com/jepbura/go-server/pkg/repository"
	"github.com/jepbura/go-server/pkg/usecase"
	mongo2 "go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeAPP(cnf config.Env) (*http.ServerHTTP, error) {
	logger, err := logging.LoggerInit(cnf)
	if err != nil {
		return nil, err
	}
	client, err := mongo.NewMongoDatabase(cnf, logger)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}

// wire.go:

type App struct {
	Client *mongo2.Client
	// DbProvider *mongodb.MongoDBHandler
	// Repo        *repository.UserDatabase
	// Usecase     *usecase.UserUseCase
	// UserHandler *handler.UserHandler
	Http *http.ServerHTTP
}

var dbSet = wire.NewSet(mongo.NewMongoDatabase)

var NewUserRepository = wire.NewSet(repository.NewUserRepository)

var usecaseSet = wire.NewSet(usecase.NewUserUseCase)

var handlerSet = wire.NewSet(handler.NewUserHandler)
