// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name        string `json:"name"`
	Surname     string `json:"surname"`
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	NationalID  string `json:"nationalId"`
	BirthYear   string `json:"birthYear"`
	PhoneNumber string `json:"phoneNumber"`
	FatherName  string `json:"fatherName"`
	City        string `json:"city"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	Role        string `json:"role"`
	PhotoURL    string `json:"photoURL"`
	Settings    string `json:"settings"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Surname     string `json:"surname"`
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	NationalID  string `json:"nationalId"`
	BirthYear   string `json:"birthYear"`
	PhoneNumber string `json:"phoneNumber"`
	FatherName  string `json:"fatherName"`
	City        string `json:"city"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	Role        string `json:"role"`
	PhotoURL    string `json:"photoURL"`
	Settings    string `json:"settings"`
}
